### ISSUE TITLE
review section "Main drawbacks of not able to reproduce research" 

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/reproducible-research#1]
the points under this section don't seem to correspond to the section title, "Main drawbacks of not able to reproduce research".
In episode 02

**Comment by Vathasav** [comment]
@wikfeldt I have modified text in 1bab3ad Is it OK now?

**Comment by wikfeldt** [comment]
had a brief look and it seems very good. i'll read carefully over the coming days and give feedback
