### ISSUE TITLE
Following Docker instructions causes error with snakemake

### ISSUE THREAD

**Issue by pjehkonen** [coderefinery/reproducible-research#126]
I followed instructions to build Docker image and then finally create an volume causes an error with snakemake.

Not sure how to report but, I do my best:
Commit hash: 260f318
same as page source: https://github.com/coderefinery/reproducible-research/blob/gh-pages/_episodes/07-docker.md

When executing step with instructions: 
"
$ docker run -v <path-on-hostmachine/results_directory>:/opt/word_count/results word_count:0.1 snakemake -s Snakefile_all
"

I get following error:

"
docker run -v /home/itsme/Documents/Learning/word-count/results:/opt/word_count/results word_count:0.1 snakemake -s Snakefile_all
Traceback (most recent call last):
  File "/usr/local/bin/snakemake", line 5, in <module>
    from snakemake import main
  File "/usr/local/lib/python3.5/dist-packages/snakemake/__init__.py", line 21, in <module>
    from snakemake.workflow import Workflow
  File "/usr/local/lib/python3.5/dist-packages/snakemake/workflow.py", line 23, in <module>
    from snakemake.rules import Rule, Ruleorder, RuleProxy
  File "/usr/local/lib/python3.5/dist-packages/snakemake/rules.py", line 16, in <module>
    from snakemake.io import (
  File "/usr/local/lib/python3.5/dist-packages/snakemake/io.py", line 1223
    f"{_name}() cannot be used; attribute name reserved"
                                                       ^
SyntaxError: invalid syntax

"

**Comment by pjehkonen** [comment]
This most likely is not relevant issue. I have not used Docker before, and after raising this Issue, I noticed that I had to execute twicethe 'exit'-command to return to my normal shell. I do not know if it is possible to be inside of nested docker images such as: normal_shell_env->docker_container1->docker_container2? If the reported issue cannot be replicated, this can be closed.

**Comment by bast** [comment]
Thanks for reporting and sorry this never got a follow-up. The lesson has now been changed to critically discuss existing definition files in the context of reproducibility rather than building containers. So this is not relevant anymore but I still very appreciate raising it.
