### ISSUE TITLE
Snakemake example assumes bash

### ISSUE THREAD

**Issue by bast** [coderefinery/reproducible-research#130]
We should try to perhaps remove bash-specifics. Not everybody tries this on bash.

**Comment by bast** [comment]
Line 23 in Snakefile

**Comment by samumantha** [comment]
Do I see it right that line 23 is actually commented, so not really run? And still it gives issues for non bash users?

**Comment by wikfeldt** [comment]
no this rule is not commented, the triple apostrophe is to demarcate the command

**Comment by wikfeldt** [comment]
the echo command can be left out i think, with only `python {input.wc} {input.book} {output} >> {log} 2>&1` remaining. I think this should work on POSIX compliant shells and (according to google) should work on windows
