### ISSUE TITLE
Snakemake - solutions (helper help)

### ISSUE THREAD

**Issue by samumantha** [coderefinery/reproducible-research#132]
I feel like helpers were a bit overwhelmed by the snakemake exercise. I would suggest to either include it in the helper preparation (as optional part), or add some 'solution' help. What should they be seeing and why. etc

**Comment by rkdarst** [comment]
I am very for this.  I feel terrified of doing anything with snakemake
in 20 minutes, and I've even spent too long preparing for a RSH
presentation on it...

**Comment by samumantha** [comment]
working on this. Is there a way to add this hidden solution box here, or should the walkthrough with solutions be somewhere else but the lesson material?

**Comment by samumantha** [comment]
Or what do you think of changing the exercise to a more walkthrough than 'think yourself' exercise. I.e. rather explaining what each comment does and why, than asking questions?

**Comment by bast** [comment]
I think this could be more useful. Although in the past when we had more time and less install troubles, we also got good feedback for the current form. But personally I think a demo and discussion could have a better learning outcome.

**Comment by samumantha** [comment]
As discussed with Radovan and Anne in zoom chat: We think the exercise is very helpful for learners but needs some time before for the instructor to go through the lesson to make clear *what* and *why* snakemake. Breakoutroom session is then there to play around and get an understanding of the *how*.
