### ISSUE TITLE
cognitive overload when this lesson taught before mybinder is introduced in Jupyter lesson

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/reproducible-research#140]
when [Snakemake type-along and exercise](https://coderefinery.github.io/reproducible-research/04-workflow-management/) are done on mybinder.org, there's a lot of new stuff for many learners: mybinder, snakemake, make, ...

consider either properly introducing mybinder, or having reproducibility lesson after jupyter lesson.

**Comment by johanhellsvik** [comment]
This is a good point. With the new (May 2021) conda 'coderefinery' environment, we have the option to run the snakemake type-along and exercise on the local computers instead of on mybinder. This is something to consider.
