### ISSUE TITLE
Citing & publishing software: Publishing research software

### ISSUE THREAD

**Issue by bast** [coderefinery/reproducible-research#144]
I was made aware of this resource which we could link to:
https://libguides.mit.edu/software

**Comment by johanhellsvik** [comment]
Good suggestion. I have added a link, unintentionally working on the gh-pages branch. Was puzzled why I could not see a make pull request button on GitHub after pushing :-)
https://github.com/coderefinery/reproducible-research/commit/491ee6464a5c2ba59aa761b1892edcb023c9e905
