### ISSUE TITLE
Links to install of docker and make are broken

### ISSUE THREAD

**Issue by johanhellsvik** [coderefinery/reproducible-research#146]
Under the heading prerequisities https://coderefinery.github.io/reproducible-research/#prerequisites
the links to install of docker and make are broken.

**Comment by bast** [comment]
Ah yes sorry. I broke (removed) those. Should I somehow bring these back?

**Comment by johanhellsvik** [comment]
It would be good to have them back. Please note that on the May 2021 workshop we will not cover
https://github.com/coderefinery/reproducible-research/blob/gh-pages/extra/make-alternative.md
https://github.com/coderefinery/reproducible-research/blob/gh-pages/extra/make-alternative.md
in session - so in that regard there is no urgency on the matter.

**Comment by bast** [comment]
Good. Let's bring them back but I think the Docker might need some refreshing so it's not just un-deleting. I will try to do this before this workshop.

**Comment by wikfeldt** [comment]
fixed now
