### ISSUE TITLE
include material on data management

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/reproducible-research#16]
We need at least 0.5h module on data in a 3-day workshop, and it might fit into this lesson. Discuss e.g. file formats, databases, flat files...

**Comment by rkdarst** [comment]
+1, if needed ask me to make something.  I personally don't have material on fancy tools prepared, but I do have plenty of other stuff.

**Comment by wikfeldt** [comment]
it would be great if you could add something on data management! what did you have in mind?

**Comment by wikfeldt** [comment]
this is partly addressed in #27, but would be good to have more material and a dedicated episode (which could be optional)

**Comment by bast** [comment]
This issue is 1.5 years old. I think the lesson has a data aspect, we list many useful links. More data focus would be always welcome but I don't think carrying this issue into the next year will help us with that. PRs always welcome. Closing for now.
