### ISSUE TITLE
Step 4 in Exercise: "Get a DOI by connecting you repository to Zenodo"

### ISSUE THREAD

**Issue by NMoksnes** [coderefinery/reproducible-research#163]
Step 4 says that you should release, however that function is not available in GitHub anymore.
![Capture](https://user-images.githubusercontent.com/30128518/118622962-13e44000-b7c8-11eb-9758-05a8c5ac8f49.JPG)

**Comment by bast** [comment]
It's on the right-hand panel. We need to update description. Thanks!
