### ISSUE TITLE
Create a list of exercises

### ISSUE THREAD

**Issue by bast** [coderefinery/reproducible-research#170]
Within the lesson, not in an outside document. This will make it easier to onboard helpers. Creating this overview also helped me to see the bigger picture of the lesson and to identify gaps.

**Comment by wikfeldt** [comment]
i'll add this to the instructor guide!

**Comment by bast** [comment]
I would add it to the index, like here: https://coderefinery.github.io/git-intro/ (bottom left)

**Comment by wikfeldt** [comment]
ok sure

**Comment by bast** [comment]
Reasons:
- easier to share with helpers who may not be interested in everything else that might be relevant for instructors
- instructor guides do not seem to be actually read; I have seen tons of outdated text when going through some
