### ISSUE TITLE
Get word-count repository from template only when needed

### ISSUE THREAD

**Issue by samumantha** [coderefinery/reproducible-research#175]
A thought:
Currently the word-count repository is got from template in organizing your project lesson exercise (which may easily be overread there, that everyone should do this even though the exercise is demoed by instructor). But nothing is done with it then, and afterwards comes the conda exercise where it is also not used. 
It will then be used in the snakemake exercise, so why not do the get from template as part of the snakemake exercise? Did I oversee why this should be done already in the earlier lesson @wikfeldt ?

**Comment by samumantha** [comment]
Ah ok, now while watching the recording of May CR workshop I understand why it is there. Since the instructor anyway has to do it at the point of first exercise, it is easier for participants to follow along then. 
Or could the instructor do the first exercise (which is just looking at the repo) also in the original repo? Leaving the whole create from template thingy in the snakemake exercise?

**Comment by bast** [comment]
Good point, I would also find it simpler to teach and follow to perhaps not even clone the repository but to browse it online and discuss what we see online and only generate from template and clone later. I think it would flow better and also remind us that we can do quite a lot directly in the browser.

**Comment by wikfeldt** [comment]
yes, good observation. I agree to moving the word-count template-importing to the snakemake exercise
