### ISSUE TITLE
Snakemake in HPC

### ISSUE THREAD

**Issue by samumantha** [coderefinery/reproducible-research#178]
In "your" supercomputer, is the internal snakemake HPC integration working and is it recommended to use it?
@Sabryr @bast @dianaiusan @eglerean @johanhellsvik @wikfeldt ?

As far as I understood ( and I will ask a bit more about it/test it asap), in CSC it is not recommended/not working, but one can use it within a SLURM script, without using snakemakes own HPC integration.

**Comment by bast** [comment]
I haven't tested it and I don't know the answer unfortunately.

**Comment by johanhellsvik** [comment]
Good question. To my knowledge snakemake is not actively used at Dardel which is PDC's present supercomputer. Perhaps on the earlier system Tegner. On Dardel we have started to use ReFrame https://reframe-hpc.readthedocs.io/en/stable/ .
