### ISSUE TITLE
Type along introductions to Snakemake

### ISSUE THREAD

**Issue by rantahar** [coderefinery/reproducible-research#185]
The Snakemake file in the word-count repository is long and seems confusing unless you already know Snakemake.

It might be better for clarity and for timing to write a short Snakefile from scratch instead of displaying an existing one. A short example with only one rule to take in a single file and produce a single file.

**Comment by wikfeldt** [comment]
i definitely see the value of that, and it's actually how the lesson used to be. But a common opinion back then was that the episode was too focused on how Snakemake works and had too little of a general overview

**Comment by rantahar** [comment]
Another possibility: Do a type-along exercise first. Show what SnakeMake does before showing the Snakefile. Then do the exercise and only at the end show the contents of the file and explain what the rule is.
