### ISSUE TITLE
Faster explanation of snakemake

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/reproducible-research#202]
For the snakemake episode, I tried to use the strategy "minimal explanation, let people go to exercises and give people the most time to do the exercise (and read more of the text to learn what I didn't say).

But, some feedback was that I should have done a better introduction to Snakemake to show what it actually is.  I tried to, but with a goal of five minutes of intro, that requires better planning and maybe re-focused episode text.

My first thought is a rework of the first part of the episode thinking about the above.  Not necessarily reducing text but thinking about the order and emphasis.

**Comment by bast** [comment]
I have significantly shortened the episode in terms of reading and explaing.
