### ISSUE TITLE
Detailed day schedule

### ISSUE THREAD

**Issue by bast** [coderefinery/reproducible-research#203]
This was the schedule at our last workshop:

* 08:50 - 09:00 Soft start and icebreaker question
* 09:00 - 09:10 Intro to week 2
* 09:10 - 11:15 [Reproducible research](https://coderefinery.github.io/reproducible-research/)
    - 09:10 - 09:15 [Motivation](https://coderefinery.github.io/reproducible-research/motivation/)
    - 09:15 - 09:25 [Organizing your projects](https://coderefinery.github.io/reproducible-research/organizing-projects/)
    - 09:25 - 10:00 [Recording dependencies](https://coderefinery.github.io/reproducible-research/dependencies/)
        - discussion (5 min)
        - [breakout room exercise (25 min)](https://coderefinery.github.io/reproducible-research/dependencies/#exploring-conda-environments)
        - discussion (5 min)
    - 10:00 - 10:10 Break
    - 11:00 - 10:30 [Recording computational steps](https://coderefinery.github.io/reproducible-research/workflow-management/)
       - discussion (5 min)
       - [breakout room exercise (20 min)](https://coderefinery.github.io/reproducible-research/workflow-management/#using-snakemake)
       - discussion (5 min)
    - 10:30 - 10:45 [Recording environments](https://coderefinery.github.io/reproducible-research/environments/)
      - Demo (type-along optional)
    - 10:45 - 11:15 [Sharing code and data](https://coderefinery.github.io/reproducible-research/sharing/)
        - discussion (10 min) and [demo/type-along (10 min)](https://coderefinery.github.io/reproducible-research/sharing/#connecting-repositories-to-zenodo)
    - 11:05 - 11:15 Break
* 11:15 - 12:30 Social coding and open software
    - no group exercises
    - all interaction via hackmd

**Comment by MatiasJJ** [comment]
Change the 25 min exercise from conda to https://coderefinery.github.io/reproducible-research/dependencies/#exercise-different-solutions-to-specify-requirements

**Comment by MatiasJJ** [comment]
Change times in the lesson pages top
