### ISSUE TITLE
Latest version used snakemake, no install instructions

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/reproducible-research#22]
This person was using windows.  The conda install instructions on the snakemake site didn't work.  Also the windows installation instructions didn't work.  (both said package not found in the requested channels).

This person's computer had plenty of problems and I'm not sure if the environment was set up correctly.  The problems mostly seem related to confusion about (git bash shell vs anaconda shell (windows shell)) and conda environments and and environment variables.

Anyway, if installation instructions work on other windows computer (win10), then you can probably just close this issue.

**Comment by wikfeldt** [comment]
was the person using python3? Snakemake requires version >=3.4, which is actually mentioned on https://coderefinery.github.io/installation/python/#snakemake-1

**Comment by rkdarst** [comment]
I did check the python version, it said 3.6.  But now I think it's likely, or at least possible, that the conda and python binaries pointed to different things so conda may have been python2.  It was windows and windows shell so I couldn't do much.

One other problem was no make installed - it wasn't in instructions for the espoo workshop.  He found them from the past workshop but didn't put them into the windows PATH...

All in all, as long as instructions should theoretically work, we can close this.

**Comment by wikfeldt** [comment]
we now emphasize that python3 is recommended, and the snakemake install instructions make it clear that python2 won't work. so closing this issue
