### ISSUE TITLE
Please verify list of exercises

### ISSUE THREAD

**Issue by bast** [coderefinery/reproducible-research#248]
@samumantha @eglerean can you please check that the list here for your session is correct?

https://coderefinery.github.io/2023-09-19-workshop/exercises/

**Comment by samumantha** [comment]
I would remove the dependencies exercise and give 5 more min to workflows exercise. But let's wait for @eglerean opinion.

**Comment by bast** [comment]
I will adjust the page based on detailed schedule so don't worry about it now.

**Comment by samumantha** [comment]
- [ ] mark exercises not planned to be done in workshop as "optional"
