### ISSUE TITLE
compare containers to VMs

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/reproducible-research#47]
since the differences are important

**Comment by Sabryr** [comment]
would it be too much if we have "virtual environments" in this comparison as well. My personal favourite to overcome hard compiled binaries is conda, not containers.

**Comment by annefou** [comment]
I definitely agree with you @Sabryr . I just discussed last week about developing a short tutorial on how to add new packages in conda.

**Comment by wikfeldt** [comment]
good point, i'll generalize the Containers episode to cover also conda and perhaps pipenv.

**Comment by bast** [comment]
Yay for pipenv :-)

**Comment by annefou** [comment]
is pipenv for python only or is it like conda (language agnostic)?

**Comment by Sabryr** [comment]
pipenv is only for python packages (it could contain compiled C) for example things you install with pip install. Conda is actually package manager in a sense. On Abel  (out HPC cluster) I have several kernel dependent packages in conda with all binaries and GLIBC.

**Comment by wikfeldt** [comment]
good reference for the git+snakemake+conda+docker reproducible combo is this NBIS course:
https://nbis-reproducible-research.readthedocs.io/en/latest/
