### ISSUE TITLE
add tools (logos) to "levels of reproducibility" image

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/reproducible-research#5]
remove sumatra (too narrow in scope), add CWL, zenodo, figshare, etc

**Comment by Vathasav** [comment]
I see that CWL fits into data and documentation level. Zenodo, figshare at data level, as they help to archive the data. Am I wrong?

**Comment by bast** [comment]
Good idea!

**Comment by wikfeldt** [comment]
yes i like it, can you do it Harsha or can you add an svg to the repo?
