### ISSUE TITLE
Add notes for conda in HPC environment

### ISSUE THREAD

**Issue by tprossi** [coderefinery/reproducible-research#59]
Notes raised in Gothenburg workshop regarding conda and performance / filesystem burden in HPC environment:
* Option to specify build (e.g., MKL vs openblas)
* Environment location `conda create -n NAME` vs `conda create -p PATH` (non-backed-up filesystem can be preferred)
* `conda clean` to clean cached files

**Comment by bast** [comment]
Thank you!
