### ISSUE TITLE
Move conda to before the snakemake section

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/reproducible-research#62]
With new schedule, this is the first lesson where we needed the conda environment (for snakemake).  Thus, I had to briefly explain the concept of conda environments, enough to make "and now I activate my conda environment" make sense.  But conda is introduced in the last section after snakemake.

It does make sense with virtual environments in some sense, but perhaps flow could be made better by splitting conda and docker (the section gets quite long) and putting conda earlier.

**Comment by bast** [comment]
I had the same feeling and am working on moving the environments session in front of workflows. Workflows are important but I think venv/conda/pipenv is even more important and closer to real life of what participants already do and have and if it's at the end, we never have time for this.

**Comment by bast** [comment]
I also want to decouple that section from snakemake and not use snakemake as an example here.

**Comment by bast** [comment]
I consider requirements.txt/Pipenv a must have. Snakemake and workflow tools are nice to have.

**Comment by wikfeldt** [comment]
conda is now introduced before snakemake, closing issue
