### ISSUE TITLE
make/snakemake: include a two-target makefile example

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/reproducible-research#63]
I suggest there be a two-rule Makefile, with the output of one rule the input of another (at the very top of the file).  I had to explain the concept of dependencies there, and a real example to point at would have helped (in place of / below the one with target/dependencies/command in it).

**Comment by wikfeldt** [comment]
a makefile (albeit more complicated than two rules) is now shown under https://coderefinery.github.io/reproducible-research/06-workflow-management/#solution-4-using-gnu-make
Dependencies are discussed at this point in the lesson so hopefully this issue is resolved.
