### ISSUE TITLE
Add pyenv as an option for virutal environments

### ISSUE THREAD

**Issue by blankdots** [coderefinery/reproducible-research#64]
I found https://github.com/pyenv/pyenv to be a better option after suggesting it to some of my colleagues, even more so for those that had no experience with python, as it can be set as a global version and no need to change further.

**Comment by bast** [comment]
But better option than what precisely?

**Comment by bast** [comment]
Aha better option to virtual envs? As far as I understand they are complementary: pyenv is for the Python version, virtual env is for Python packages. There is also pipenv and poetry.

**Comment by blankdots** [comment]
yes, "better" that is relative, yes there is `pipenv`and others, but i think in terms of getting starting fresh without any knowledge of activating, deactivating virtual environments etc. it provides a good enough alternative.

Still would be nice to add it as an option.

**Comment by bast** [comment]
I agree that we can add it as an option.

**Comment by bast** [comment]
In my (mis)understanding, pyenv is not an alternative for package management but only for Python version management. We should still mention it but IMO it does not replace venv/pipenv/...

**Comment by wikfeldt** [comment]
this was added in c7d3a96813cb55518c4c6cb99eeb05b3fae71118
closing issue
