### ISSUE TITLE
Docker analogies

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/reproducible-research#68]
When reviewing the lesson some time ago, I remember the docker analogy of images/containers not being very good, so have been trying to come up with a better one.  Here's the best I have so far (does anyone have something better?):

A docker container is like a piece of paper with all the operating system on it.  When you run it, a transparent sheet is placed on top to form a container.  The container runs and writes only on that transparent sheet (and what other mounts have been layered on top).  When you are done, transparency is thrown away.  It can be repeated as often as you want, and base is always the same.

Analogy breaks down when you use the same base to run multiple containers without copying the base.  But it works when you discuss how images are composed (multiple transparent sheets stacked on top of each other, not that we go into it).

**Comment by rkdarst** [comment]
I think we can basically use what they use, but with the right thing being shipped: you copy your base paper many times, send it to every one that needs to run your stuff, they add in their own transparency on top and can reproduce your stuff.  Their analogy is just a bit bad because the container doesn't hold stuff that gets taken out (and in docker terms its the image, not "container", that moves)

**Comment by bast** [comment]
This is similar to this nice explanation: https://twitter.com/b0rk/status/1196469601938411521
