### ISSUE TITLE
Exercise on adding requirements.txt or equivalent to a project

### ISSUE THREAD

**Issue by bast** [coderefinery/reproducible-research#70]
It can also be used to detect hidden dependencies (e.g. exercise has a few things declared in the README, but a hidden function imports something else).

Followed-up from https://github.com/coderefinery/reproducible-research/pull/66#issuecomment-512308641.

**Comment by wikfeldt** [comment]
fixed in b978e3febc3df7bae894334542172d601a3f64be
closing
