### ISSUE TITLE
Change license from CC-BY-SA to CC-BY

### ISSUE THREAD

**Issue by bast** [coderefinery/reproducible-research#76]
Motivation (discussion on the Carpentries mailing list): https://carpentries.topicbox.com/groups/discuss/Td64229aeb252a027

In short, the motivation is to simplify reuse for those who wish to take parts of our lessons and remix them into material which is CC-BY.

At the team meeting 2019-08-12 we have decided to change the license to CC-BY provided that all contributors to this lesson material agree to this change.

This issue will track the progress of this change.

**Comment by bast** [comment]
@Vathasav @wikfeldt can you please comment whether you agree to this change?

**Comment by bast** [comment]
I agree to a license change to CC-BY. Richard agrees via https://github.com/coderefinery/git-intro/issues/192#issuecomment-521359880.

**Comment by wikfeldt** [comment]
I agree to a license change to CC-BY

**Comment by Vathasav** [comment]
I agree to a license change to CC-BY.
