### ISSUE TITLE
addition of LICENSE file breaks jekyll on macOSX

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/reproducible-research#79]
commit 778bc21 added a file LICENSE. Most Macs have a case-insensitive file system, and since the jekyll build tries both to create the file _site/LICENSE and the directory _site/license/ the build fails with error:
```
jekyll 3.6.2 | Error:  Operation not permitted @ unlink_internal - <PATH>/reproducible-research/_site/LICENSE
```
this problem arises also for all other lesson repositories where a LICENSE file was introduced

**Comment by bast** [comment]
A fix might be (untested) to put this into `_config.yml`:
```yaml
exclude: ["LICENSE"]
```
