### ISSUE TITLE
add more data archiving and sharing services for Norway

### ISSUE THREAD

**Issue by arockenberger** [coderefinery/reproducible-research#90]
In [episode 03](https://github.com/coderefinery/reproducible-research/blob/gh-pages/_episodes/03-sharing.md), under [Services for Sharing…](https://github.com/coderefinery/reproducible-research/blob/gh-pages/_episodes/03-sharing.md#services-for-sharing-and-collaborating-on-research-data), add a couple more services for Norway, e.g.

[NSD - Norwegian Center for Research Data](https://nsd.no/nsd/english/index.html), initially created for Social Sciences and Humanities Data, but open for and used for any kind of data
[TSD - Norwegian Service for Sensitive Data](https://www.uio.no/english/services/it/research/sensitive-data/about/index.html), based at University of Oslo, but open for researchers from other institutions, too.
[Dataverse.no - Dataverse network based at University of Tromsø](https://dataverse.no/), based at UiT but open for researchers from other institutions, regardless of their field. Limit to the size of data (up to 1GB for free).

**Comment by bast** [comment]
Thanks a lot for these!
