### ISSUE TITLE
probably completely remove make example

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/reproducible-research#96]
it's overkill to show both make and snakemake, and showing both reduces the time available to go into interesting details

**Comment by bast** [comment]
I don't think we need to spend more than 10 minutes on `make` and it provides a nice progression to snakemake. But I understand that it would be nice to save the 10 minutes also. I would keep make as optional and mention it and spend most of the time and also exercise time on the snakemake part. Anyway, both are there only as an example. I am still looking for a tool that would appeal to participants with all programming language backgrounds.

**Comment by wikfeldt** [comment]
fixed in #110
